server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    connection-timeout: 20000

netty:
  # netty 端口
  port: 8088
  # websocket 路径
  websocketPath: ws

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: fan
    password: Fmy1054.
    url: jdbc:mysql://106.14.120.166:3400/chat?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      max-active: 500
      min-idle: 1
      max-wait: 60000

  redis:
    host: 127.0.0.1
    port: 6379
#    password: myredis
    timeout: 3000
    database: 0
    jedis:
      pool:
        #最大连接数
        max-active: 30
        #最大空闲时间
        max-idle: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true

  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  session:
    store-type: redis
    timeout: 300

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: edu.sandau.chat.entity, edu.sandau.chat.vo, edu.sandau.chat.netty
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true
logging:
  pattern:
    console:
